---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: victoria-metrics
spec:
  policyRef:
    name: victoria-metrics
  schedule:
    concurrencyPolicy: Forbid
    cron: "0 */12 * * *"
    runOnCreate: false
