---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoria-metrics-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: victoria-metrics-volsync-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_REPOSITORY: filesystem:///mnt/repository
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: victoria-metrics-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 8Gi
    cacheStorageClassName: openebs-hostpath
    capacity: 50Gi
    copyMethod: Snapshot
    enableFileDeletion: true
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /backups/volsync-kopia
            server: normandie.internal
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    repository: victoria-metrics-volsync-secret
    sourceIdentity:
      sourceName: victoria-metrics
      sourceNamespace: observability
    storageClassName: openebs-zfs
    volumeSnapshotClassName: openebs-snapshots
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: victoria-metrics
spec:
  sourcePVC: vmsingle-victoria-metrics
  trigger:
    schedule: 0 */6 * * *
  kopia:
    accessModes:
      - ReadWriteOnce
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    parallelism: 2
    repository: victoria-metrics-volsync-secret
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /backups/volsync-kopia
            server: normandie.internal
    retain:
      hourly: 24
      daily: 7
    storageClassName: openebs-zfs
    volumeSnapshotClassName: openebs-snapshots
