---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: CreateReplace
  interval: 1h
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    cleanPrometheusOperatorObjectNames: true
    coreDns:
      enabled: false
    crds:
      enabled: true
    defaultRules:
      create: false
    grafana:
      defaultDashboardsEnabled: true
      enabled: false
      forceDeployDashboards: true
      operator:
        dashboardsConfigMapRefEnabled: true
        folder: Kubernetes
        matchLabels:
          dashboards: grafana
        resyncPeriod: 10m
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kubelet:
      enabled: false
    kubernetesServiceMonitors:
      enabled: false
    nodeExporter:
      enabled: false
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: false
    windowsMonitoring:
      enabled: false
