---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-ovh-secret
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-ovh-secret
    creationPolicy: Owner
  data:
    - secretKey: OVH_APPLICATION_KEY
      remoteRef:
        key: ovh
        property: OVH_APPLICATION_KEY
    - secretKey: OVH_APPLICATION_SECRET
      remoteRef:
        key: ovh
        property: OVH_APPLICATION_SECRET
    - secretKey: OVH_CONSUMER_KEY
      remoteRef:
        key: ovh
        property: OVH_CONSUMER_KEY
