---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gomuks
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: gomuks
  interval: 1h
  path: ./kubernetes/apps/matrix/gomuks/app
  components:
    - ../../../../components/oidc/envoy
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: kanidm
      namespace: security
  postBuild:
    substitute:
      APP: gomuks
      APP_NAMESPACE: matrix
      OIDC_DISPLAY_NAME: Gomuks
      OIDC_GROUP: admins
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  timeout: 5m
  wait: false
