---
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kromgo/main/config.schema.json
defaults:
  hidden: false

badge:
  size: 12

metrics:
  - name: talos_version
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    value: labels["version_id"]
    title: Talos

  - name: kubernetes_version
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    value: labels["git_version"]
    title: Kubernetes

  - name: flux_version
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    value: labels["revision"]
    title: Flux

  - name: mkt_version
    query: label_replace(mktxp_system_uptime, "short_version", "$1", "version", "([^ ]+).*")
    value: labels["short_version"]
    title: MikroTik

  - name: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    color: '"green"'
    title: Nodes

  - name: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    value: humanizeNumber(result)
    color: '"green"'
    title: Pods
    timeseries:
      enabled: true
      maxDuration: "7d"

  - name: github_last_push_info
    query: label_replace(topk(1, github_last_push_info), "short_repo", "$1", "repo", ".+/(.+)")
    value: labels["short_repo"]
    title: Last Push

  - name: github_last_push_timestamp
    query: topk(1, github_last_push_info)
    title: Last Push Age

  - name: gh_contributions_year
    query: avg(gh_contributions_year)
    title: GH Contributions (1y)
    timeseries:
      enabled: true
      maxDuration: "1y"

  - name: github_followers
    query: github_followers
    title: Followers
    timeseries:
      enabled: true
      maxDuration: "0"

  - name: github_public_repos
    query: github_public_repos
    title: Public Repos

  - name: github_stars_total
    query: github_stars_total
    title: Stars
    timeseries:
      enabled: true
      maxDuration: "0"

  - name: cluster_latency_over_7d
    query: quantile(0.99, gatus_results_duration_seconds)
    value: string(result) + "s"
    color: 'result <= 300 ? "green" : result <= 700 ? "orange" : "red"'
    title: Gateway Latency
    timeseries:
      enabled: true
      maxDuration: "7d"

  - name: cluster_cpu_usage
    query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
    value: string(result) + "%"
    color: 'result <= 35 ? "green" : result <= 75 ? "orange" : "red"'
    title: CPU
    timeseries:
      enabled: true
      maxDuration: "7d"

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
    value: string(result) + "%"
    color: 'result <= 49 ? "green" : result <= 75 ? "orange" : "red"'
    title: Memory
    timeseries:
      enabled: true
      maxDuration: "7d"

  - name: cluster_age_days
    query: round((time() - max(kube_node_created)) / 86400)
    value: string(result) + "d"
    color: 'result <= 180 ? "green" : result <= 360 ? "orange" : "red"'
    title: Age

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
    value: string(result) + "d"
    color: 'result <= 180 ? "green" : result <= 360 ? "orange" : "red"'
    title: Uptime

  - name: cluster_alert_count
    query: ALERTS{alertstate="firing"} - 1
    color: 'result < 1 ? "green" : "red"'
    title: Alerts

  - name: global_sla
    query: |
      sum(increase(gatus_results_total{success="true"}[7d]))
      /
      sum(increase(gatus_results_total[7d]))
      * 100
    value: string(result) + "%"
    color: 'result >= 99.9 ? "green" : result >= 99.0 ? "orange" : "red"'
    title: SLA (7d)
    timeseries:
      enabled: true
      maxDuration: "7d"
