# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app piefed
spec:
  components:
    - ../../../../components/anubis
    - ../../../../components/postgres/pass
    - ../../../../components/kopiur/hot
  dependsOn:
    - name: cnpg-cluster
      namespace: database
    - name: dragonfly-operator
      namespace: dragonfly-system
    - name: kopiur-repository
      namespace: kopiur-system
    - name: openebs
      namespace: openebs-system
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  interval: 1h
  path: ./kubernetes/apps/selfhosted/piefed/app
  postBuild:
    substitute:
      APP: *app
      ANUBIS_TARGET: http://piefed-app.selfhosted.svc:5000
      APP_NAMESPACE: selfhosted
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: photon
spec:
  dependsOn:
    - name: kopiur-repository
      namespace: kopiur-system
    - name: piefed
      namespace: selfhosted
  interval: 1h
  path: ./kubernetes/apps/selfhosted/piefed/photon
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
