---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmalert_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vlogs
spec:
  datasource:
    url: http://victoria-logs-client.observability.svc.cluster.local:9428
  evaluationInterval: 15s
  extraArgs:
    remoteWrite.disablePathAppend: "true"
    rule.defaultRuleType: vlogs
  notifiers:
    - url: http://vmalertmanager-victoria-metrics-0.vmalertmanager-victoria-metrics.observability.svc.cluster.local:9093
  remoteRead:
    url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428
  remoteWrite:
    url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428/api/v1/write
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 200Mi
  ruleSelector:
    matchLabels:
      vmalert-datasource: vlogs
  selectAllByDefault: false
