---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: prometheus-adapter-rules-vlogs
  labels:
    vmalert-datasource: vlogs
spec:
  groups:
    - name: envoy-route-requests-vlogs
      interval: 15s
      type: vlogs
      rules:
        - record: envoy_route_requests_log
          expr: |-
            kubernetes.pod_namespace:network kubernetes.container_name:envoy envoy_route:httproute/* _time:2m
            | extract "httproute/<_>/<route_name>/rule/<_>" from envoy_route
            | filter route_name:*
            | stats by(route_name) count() value
