---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lemmy-config
data:
  config.hjson: |-
    {
      hostname: "lemmy.erwanleboucher.dev"
      pictrs: {
        url: "http://lemmy-pictrs:8080/"
      }
      email: {
        connection: "smtp://smtp-relay.selfhosted.svc.cluster.local:25"
        smtp_from_address: "noreply@lemmy.erwanleboucher.dev"
      }
    }
