---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lemmy
spec:
  chartRef:
    kind: OCIRepository
    name: lemmy
  interval: 30m
  values:
    controllers:
      pictrs:
        pod:
          securityContext:
            fsGroup: 991
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: docker.io/asonix/pictrs
              tag: 0.5.23
            env:
              RUST_BACKTRACE: full
              PICTRS__MEDIA__ANIMATION__MAX_FRAME_COUNT: "400"
              PICTRS__MEDIA__ANIMATION__MAX_HEIGHT: "256"
              PICTRS__MEDIA__ANIMATION__MAX_WIDTH: "256"
              PICTRS__MEDIA__VIDEO__VIDEO_CODEC: vp9
              PICTRS__SERVER__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lemmy-pictrs-key
                    key: api_key
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              runAsGroup: 991
              runAsUser: 991

      server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/dessalines/lemmy
              # renovate: datasource=docker depName=docker.io/dessalines/lemmy
              tag: 1.0.0-beta.0
            env:
              RUST_LOG: warn
              LEMMY__EMAIL__CONNECTION: smtp://smtp-relay.selfhosted.svc.cluster.local:25
              LEMMY__EMAIL__SMTP_FROM_ADDRESS: noreply@lemmy.erwanleboucher.dev
              LEMMY__HOSTNAME: lemmy.erwanleboucher.dev
              LEMMY__PICTRS__URL: http://lemmy-pictrs:8080/
              LEMMY__DATABASE__URI:
                valueFrom:
                  secretKeyRef:
                    name: lemmy-postgres
                    key: url
              LEMMY__PICTRS__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lemmy-pictrs-key
                    key: api_key
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

      ui:
        containers:
          app:
            image:
              repository: docker.io/dessalines/lemmy-ui
              # renovate: datasource=docker depName=docker.io/dessalines/lemmy-ui
              tag: 1.0.0-beta.0
            env:
              LEMMY_UI_BACKEND: https://lemmy.erwanleboucher.dev
              LEMMY_UI_BACKEND_INTERNAL: http://lemmy:8536
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    persistence:
      config:
        type: configMap
        name: lemmy-config
        advancedMounts:
          server:
            app:
              - path: /config/config.hjson
                subPath: config.hjson
      pictrs-data:
        type: persistentVolumeClaim
        existingClaim: lemmy
        advancedMounts:
          pictrs:
            app:
              - path: /mnt

    route:
      app:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - lemmy.erwanleboucher.dev
        rules:
          - matches:
              - method: POST
            backendRefs:
              - identifier: app
                port: 8536
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
              - path:
                  type: PathPrefix
                  value: /pictrs
              - path:
                  type: PathPrefix
                  value: /feeds
              - path:
                  type: PathPrefix
                  value: /nodeinfo
              - path:
                  type: PathPrefix
                  value: /.well-known
              - path:
                  type: PathPrefix
                  value: /inbox
              - path:
                  type: Exact
                  value: /version
              - path:
                  type: Exact
                  value: /sitemap.xml
            backendRefs:
              - identifier: app
                port: 8536
          - backendRefs:
              - identifier: ui
                port: 1234

    service:
      app:
        controller: server
        ports:
          http:
            port: 8536
      pictrs:
        controller: pictrs
        ports:
          http:
            port: 8080
      ui:
        controller: ui
        ports:
          http:
            port: 1234
