---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lk-jwt-service
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lk-jwt-service
    creationPolicy: Owner
    template:
      data:
        LIVEKIT_KEY: "{{ .api_key }}"
        LIVEKIT_SECRET: "{{ .api_secret }}"
  dataFrom:
    - extract:
        key: livekit
