---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openclaw
  namespace: flux-system
spec:
  components:
    - ../../../../components/kopiur/hot
  dependsOn:
    - name: external-secrets
      namespace: security
    - name: kopiur-repository
      namespace: kopiur-system
    - name: miroir
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/openclaw/openclaw/app
  postBuild:
    substitute:
      APP: openclaw
      APP_NAMESPACE: openclaw
      KOPIUR_CAPACITY: 10Gi
      KOPIUR_SNAPSHOTCLASS: miroir-snap
      KOPIUR_STORAGECLASS: miroir-replicated
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: openclaw
  timeout: 5m
  wait: false
