---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agentgateway-crds
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway-crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: agentgateway-crds
      namespace: ai
  interval: 1h
  path: ./kubernetes/apps/ai/agentgateway/crds
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agentgateway
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway
  dependsOn:
    - name: agentgateway-crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: agentgateway
      namespace: ai
  interval: 1h
  path: ./kubernetes/apps/ai/agentgateway/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agentgateway-config
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway-config
  dependsOn:
    - name: agentgateway
  interval: 1h
  path: ./kubernetes/apps/ai/agentgateway/config
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
