---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coturn
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coturn
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: coturn-configmap
            items:
              - key: turnserver.conf
  dataFrom:
    - extract:
        key: continuwuity
