---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./mcp-secrets.yaml
  - ./mcp-talos-serviceaccount.yaml
  - ./litellmproxy.yaml
  - ./litellmmodels.yaml
  - ./litellmmcpservers.yaml
  - ./grafanadashboard.yaml
  - ./servicemonitor.yaml
  - ./dashboard
