---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volsync-restart-${APP}
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/rbac.authorization.k8s.io/role_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: volsync-restart-${APP}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "statefulsets"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - "statefulsets/scale"
    verbs:
      - "update"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/rbac.authorization.k8s.io/rolebinding_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volsync-restart-${APP}
subjects:
  - kind: ServiceAccount
    name: volsync-restart-${APP}
roleRef:
  kind: Role
  name: volsync-restart-${APP}
  apiGroup: rbac.authorization.k8s.io
