---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP}-nfs-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
    - nfsvers=4.1
    - soft
    - timeo=100
    - retrans=3
  nfs:
    path: /
    server: normandie.internal
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-nfs-media
  namespace: ${APP_NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: ${APP}-nfs-media
