---
working_dir: ./docker/vps
reconciliation:
  enabled: true
auto_discovery:
  enabled: true
  depth: 1
  delete: true
force_recreate: false
external_secrets:
  FORGEJO_RUNNER_HOMELAB_UUID: "op://kubernetes/forgejo-runner-vps-homelab/uuid"
  FORGEJO_RUNNER_HOMELAB_TOKEN: "op://kubernetes/forgejo-runner-vps-homelab/token"
  FORGEJO_RUNNER_OW_OPS_UUID: "op://kubernetes/forgejo-runner-vps-ow-ops/uuid"
  FORGEJO_RUNNER_OW_OPS_TOKEN: "op://kubernetes/forgejo-runner-vps-ow-ops/token"
