# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homefs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homefs
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      tag: main@sha256:ea18878012d11cece1bf85aca37a84732d03a6f12326754210a125dbb2941827
    nodes:
      kharkiv:
        backend: lvmthin
        device: /dev/disk/by-partlabel/r-homefs
      paris:
        backend: zfs
        zfsDataset: data-pool/homefs
    storageClass:
      create: true
      name: homefs-local
      isDefault: false
    replicatedStorageClass:
      create: true
      name: homefs-replicated
      isDefault: false
      quorum: last-man-standing
    volumeSnapshotClass:
      create: true
      name: homefs-snap
