---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
spec:
  endpoints:
    - dnsName: external.erwanleboucher.dev
      recordType: CNAME
      targets:
        - edge-eu.towonel.dev
    - dnsName: erwanleboucher.dev
      recordType: A
      targets:
        - 151.80.142.238
    - dnsName: www.erwanleboucher.dev
      recordType: A
      targets:
        - 151.80.142.238
    - dnsName: openpgpkey.erwanleboucher.dev
      recordType: A
      targets:
        - 151.80.142.238
    - dnsName: registry.erwanleboucher.dev
      recordType: A
      targets:
        - 151.80.142.238
    - dnsName: turn.erwanleboucher.dev
      recordType: CNAME
      targets:
        - edge-eu.towonel.dev
