---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: flaresolverr
  interval: 1h
  values:
    controllers:
      flaresolverr:
        pod:
          securityContext:
            runAsUser: &context 1000
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"
          dnsPolicy: ClusterFirst
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/thephaseless/byparr
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/Paris"
              LOG_LEVEL: INFO
            probes:
              startup: &healthProbe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8191
                  failureThreshold: 8
                  periodSeconds: 15
                  timeoutSeconds: 15
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8191
                  periodSeconds: 30
                  timeoutSeconds: 3
              readiness: *healthProbe
            resources:
              requests:
                cpu: 20m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: flaresolverr
        internalTrafficPolicy: Local
        ports:
          http:
            port: 8191
        primary: true
    persistence:
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 512Mi
        globalMounts:
          - path: /dev/shm
