---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mautrix-whatsapp
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/postgres/pass
  dependsOn:
    - name: cnpg-cluster
      namespace: database
    - name: continuwuity
  interval: 1h
  path: "./kubernetes/apps/matrix/mautrix-whatsapp/app"
  postBuild:
    substitute:
      APP: *app
      APP_NAMESPACE: matrix
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  timeout: 5m
  wait: false
