---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

resources:
  - forgejo/ks.yaml
  - forgejo-runner/ks.yaml
  - forgejo-runner-codeberg/ks.yaml
  - forgejo-runner-ow-ops/ks.yaml
  - forgejo-runner-sable/ks.yaml
  - forgesync/ks.yaml
  - namespace.yaml
