---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/referencegrant_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: keda-interceptor-from-ai
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: ai
  to:
    - group: ""
      kind: Service
      name: keda-add-ons-http-interceptor-proxy
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/referencegrant_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: keda-interceptor-from-selfhosted
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: selfhosted
  to:
    - group: ""
      kind: Service
      name: keda-add-ons-http-interceptor-proxy
