---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name copyparty-config
spec:
  refreshInterval: "0"
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        copyparty.conf: |
          [global]
            e2dsa
            e2ts
            name: share
            shr: /share
            hist: /state/hist
            xff-hdr: x-forwarded-for
            xff-src: lan

          [accounts]
            erwan: {{ .password }}

          [/]
            /w
            accs:
              A: erwan
            flags:
              lifetime: 604800
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
