---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sparkyfitness-mcp
    creationPolicy: Owner
    template:
      data:
        authorization: "Bearer {{ .mcp_api_key }}"
  dataFrom:
    - extract:
        key: sparkyfitness
