---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: sparkyfitness-mcp
spec:
  image: docker.io/codewithcj/sparkyfitness_mcp:dev@sha256:8cd75265415714fa2bef1819105459dd8b12536131f6c9f6831b233df8874997
  transport: streamable-http
  mcpPort: 3001
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: MCP_TRANSPORT
      value: http
    - name: SPARKY_FITNESS_MCP_PORT
      value: "3001"
  secrets:
    - name: sparkyfitness-mcp
      key: api-key
      targetEnvName: SPARKY_FITNESS_API_KEY
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
