---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: sparkyfitness-mcp
spec:
  image: docker.io/codewithcj/sparkyfitness_mcp:dev@sha256:8cd75265415714fa2bef1819105459dd8b12536131f6c9f6831b233df8874997
  transport: streamable-http
  mcpPort: 3001
  groupRef:
    name: mcp-tools
  externalAuthConfigRef:
    name: sparkyfitness-mcp-auth
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: MCP_TRANSPORT
      value: http
    - name: SPARKY_FITNESS_MCP_PORT
      value: "3001"
    - name: SPARKY_FITNESS_DB_HOST
      value: postgres-rw.database.svc
    - name: SPARKY_FITNESS_DB_PORT
      value: "5432"
    - name: SPARKY_FITNESS_DB_NAME
      value: sparkyfitness
    - name: SPARKY_FITNESS_DB_USER
      value: sparkyfitness
    - name: SPARKY_FITNESS_SERVER_HOST
      value: sparkyfitness.selfhosted.svc.cluster.local
    - name: SPARKY_FITNESS_SERVER_PORT
      value: "3010"
  secrets:
    - name: sparkyfitness-postgres
      key: password
      targetEnvName: SPARKY_FITNESS_DB_PASSWORD
    - name: sparkyfitness-mcp
      key: BETTER_AUTH_SECRET
      targetEnvName: BETTER_AUTH_SECRET
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
