[tasks."apply-node"]
description = "Apply Talos config to a node"
quiet = true
usage = '''
arg "<node>"
arg "[args]" var=#true
'''
run = '''
eval "set -- ${usage_args:-}"
mise run //talos:render-config "$usage_node" | talosctl -n "$usage_node" apply-config -f /dev/stdin "$@"
'''

[tasks."download-image"]
description = "Download Talos machine image"
quiet = true
usage = 'arg "<version>"'
run = '''
SCHEMATIC="$(mise run //talos:schematic-id)"
export SCHEMATIC
gum spin --title "Downloading Talos $usage_version ..." -- \
    curl -sfL --remove-on-error --retry 5 --retry-delay 5 --retry-all-errors \
        -o "talos-$usage_version-${SCHEMATIC:0:8}.iso" \
        "https://factory.talos.dev/image/${SCHEMATIC}/$usage_version/metal-amd64.iso"
mise run //:log info "Downloaded Talos" version "$usage_version" schematic "${SCHEMATIC}"
'''

[tasks."reboot-node"]
description = "Reboot a node"
quiet = true
usage = 'arg "<node>"'
run = '''
gum confirm "Reboot node $usage_node?" --default="No" &&
    talosctl -n "$usage_node" reboot -m powercycle
'''

[tasks."render-config"]
description = "Render Talos config for a node"
quiet = true
usage = 'arg "<node>"'
run = '''
CONTROLPLANE="$(mise run //talos:machine-controller "$usage_node")"
SCHEMATIC="$(mise run //talos:schematic-id)"
export CONTROLPLANE SCHEMATIC
talosctl machineconfig patch <(mise run //:template machineconfig.yaml.j2) \
    -p @<(mise run //:template "nodes/$usage_node.yaml.j2")
'''

[tasks."reset-node"]
description = "Reset a node"
quiet = true
usage = '''
arg "<node>"
arg "[args]" var=#true
'''
run = '''
eval "set -- ${usage_args:-}"
gum confirm "Reset node $usage_node?" --default="No" &&
    talosctl -n "$usage_node" reset --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL --system-labels-to-wipe u-local-hostpath --graceful=false "$@"
'''

[tasks."shutdown-node"]
description = "Shutdown a node"
quiet = true
usage = '''
arg "<node>"
arg "[args]" var=#true
'''
run = '''
eval "set -- ${usage_args:-}"
gum confirm "Shutdown node $usage_node?" --default="No" &&
    talosctl -n "$usage_node" shutdown --force "$@"
'''

[tasks."upgrade-k8s"]
description = "Upgrade Kubernetes version on the cluster"
quiet = true
usage = 'arg "<version>"'
run = '''
controller="$(talosctl config info -o yaml | yq -e '.endpoints[0]')"
talosctl -n "$controller" upgrade-k8s --to "$usage_version"
'''

[tasks."upgrade-node"]
description = "Upgrade Talos version on a node"
quiet = true
usage = '''
arg "<node>"
arg "[args]" var=#true
'''
run = '''
eval "set -- ${usage_args:-}"
talosctl -n "$usage_node" upgrade -i "$(mise run //talos:machine-image)" -m powercycle --timeout=10m "$@"
'''

[tasks."schematic-id"]
description = "Compute schematic id from talos/schematic.yaml.j2"
hide = true
quiet = true
run = '''
curl -sX POST --data-binary @<(mise run //:template schematic.yaml.j2) "https://factory.talos.dev/schematics" | jq -r '.id'
'''

[tasks."machine-controller"]
description = "Detect whether a node is a control-plane node"
hide = true
quiet = true
usage = 'arg "<node>"'
run = '''
mise run //:template "nodes/$usage_node.yaml.j2" | yq -e 'select(.machine) | (.machine.type == "controlplane") // ""'
'''

[tasks."machine-image"]
description = "Compute Talos install image URL"
hide = true
quiet = true
run = '''
mise run //:template machineconfig.yaml.j2 | yq -er 'select(.machine) | .machine.install.image'
'''
