---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-cpp-vulkan
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: llama-cpp-vulkan-secret
    creationPolicy: Owner
    template:
      data:
        HF_TOKEN: "{{ .llama_cpp_hf_token }}"
        LLAMA_API_KEY: "{{ .llama_cpp_api_key }}"
  dataFrom:
    - extract:
        key: llama-cpp
      rewrite:
        - regexp:
            source: "(.*)"
            target: "llama_cpp_$1"
