---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes
    creationPolicy: Owner
    template:
      data:
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: litellm
