---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentmemory-mcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: agentmemory-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: AGENTMEMORY_SECRET
      remoteRef:
        key: agentmemory
        property: AGENTMEMORY_SECRET
