---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: agentmemory-mcp
spec:
  image: registry.erwanleboucher.dev/eleboucher/agentmemory:0.9.17-e713f5f@sha256:f90101fd6cdfaadbff93bf377f4295f9017c6c562b2ffbe0d3d8189eae60b6b9
  transport: stdio
  proxyPort: 8080
  args:
    - mcp
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: AGENTMEMORY_URL
      value: http://agentmemory.ai.svc.cluster.local:3111
    - name: AGENTMEMORY_TOOLS
      value: all
  secrets:
    - name: agentmemory-mcp-secret
      key: AGENTMEMORY_SECRET
      targetEnvName: AGENTMEMORY_SECRET
