---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: agentmemory-mcp
spec:
  image: registry.erwanleboucher.dev/eleboucher/agentmemory:0.9.12-607df15@sha256:cd87a9195149bc62d8f8f537ce57db5e0541c22f2760c4c4caada90053cf0445
  transport: stdio
  proxyPort: 8080
  args:
    - mcp
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: AGENTMEMORY_URL
      value: http://agentmemory.ai.svc.cluster.local:3111
    - name: AGENTMEMORY_TOOLS
      value: all
  secrets:
    - name: agentmemory-mcp-secret
      key: AGENTMEMORY_SECRET
      targetEnvName: AGENTMEMORY_SECRET
