---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: agentmemory-mcp
spec:
  image: registry.erwanleboucher.dev/eleboucher/agentmemory:0.9.22-685943d@sha256:9f6ff9d8fca82c9df68481fbe484d1c1067eee2457b162edb95611c90b970e29
  transport: stdio
  proxyPort: 8080
  args:
    - mcp
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: AGENTMEMORY_URL
      value: http://agentmemory.ai.svc.cluster.local:3111
    - name: AGENTMEMORY_TOOLS
      value: all
  secrets:
    - name: agentmemory-mcp-secret
      key: AGENTMEMORY_SECRET
      targetEnvName: AGENTMEMORY_SECRET
