---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-signal
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mautrix-signal
    template:
      templateFrom:
        - configMap:
            name: mautrix-signal-configmap
            items:
              - key: config.yaml
              - key: registration.yaml
  dataFrom:
    - extract:
        key: mautrix-signal
