[global]
server_name = "erwanleboucher.dev"
address = ["::"]
port = 8080

database_path = "/data"
database_backup_path = "/backups"
database_backups_to_keep = 1

rocksdb_compression_algo = "zstd"
rocksdb_compression_level = 32767
rocksdb_bottommost_compression_level = 32767
rocksdb_bottommost_compression = true

# Perf tuning
cache_capacity_modifier = 2.0
max_request_size = 20971520

# DNS Optimisation
dns_cache_entries = 1_000_000
dns_timeout = 60
query_over_tcp_only = true
ip_lookup_strategy = 3

# User settings
allow_encryption = true
allow_federation = true
allow_registration = false
new_user_displayname_suffix = ""
suspend_on_register = false

allow_legacy_media = true
allow_public_room_directory_over_federation = false
lockdown_public_room_directory = true
require_auth_for_profile_requests = true
trusted_servers = ["codestorm.net", "starstruck.systems", "unredacted.org"]

admins_list = ["@genesixx:erwanleboucher.dev"]
startup_netburst_keep = 200


registration_token = "{{ .registration_token }}"
emergency_password = "{{ .emergency_password }}"


[global.well_known]
client = "https://matrix.erwanleboucher.dev"
server = "matrix.erwanleboucher.dev:443"
support_mxid = "@genesixx:erwanleboucher.dev"

[global.matrix_rtc]
foci = [{ type = "livekit", livekit_service_url = "https://livekit.erwanleboucher.dev" }]
