---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/garage.rajsingh.info/garagebucket_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: gokapi
spec:
  clusterRef:
    name: garage
    namespace: garage-system
  globalAlias: gokapi
  lifecycle:
    rules:
      - id: expire-orphans
        abortIncompleteMultipartUploadDays: 1
        expirationDays: 30
        status: Enabled
  quotas:
    maxSize: 20Gi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/garage.rajsingh.info/garagekey_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: gokapi
spec:
  bucketPermissions:
    - bucketRef:
        name: gokapi
      read: true
      write: true
  clusterRef:
    name: garage
    namespace: garage-system
  neverExpires: true
  secretTemplate:
    name: gokapi-s3
