---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: etcd-high-number-of-failed-grpc-requests
spec:
  matchers:
    - name: alertname
      value: etcdHighNumberOfFailedGRPCRequests
