---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-codeberg-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-codeberg-secret
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-codeberg
        property: codeberg_token
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: renovate-codeberg
        property: github_com_token
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: renovate-garage
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: renovate-garage
        property: secret_access_key
