---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie@sha256:9f9f53c9e07e5b2924945e6eaeb9168f7e856786d221839866ac85ccd703b3ba

  certificates:
    serverTLSSecret: postgres-server-cert
    serverCASecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-replication-cert

  storage:
    size: 8Gi
    storageClass: openebs-hostpath

  bootstrap:
    recovery:
      source: &src source

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store ovh-store

  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: postgres

  monitoring:
    enablePodMonitor: true

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
      - host all all all scram-sha-256
    pg_ident:
      - pooler-map pooler-rw all
    shared_preload_libraries:
      - "vchord"
      - "timescaledb"
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"

    extensions:
      - name: postgis
        ld_library_path:
          - system
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension-testing:3.6.3-18-trixie@sha256:dae68769e6e305d35d77fbb0043f84dedbbf962d6fb2c8e2e4065d52eb5abb54
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
      - name: timescaledb
        image:
          reference: ghcr.io/shusaan/timescaledb-testing:2.24.0-18-trixie@sha256:dae25c2dde06455214ac5553b51d3ef2d48fe84795c2cfa48c51c6e15877044e

  managed:
    roles:
      - name: paperless
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: sparkyfitness
        ensure: present
        login: true
        superuser: false
        disablePassword: false
      - name: mealie
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: pooler-rw
        ensure: present
        login: true
        superuser: false
        disablePassword: true
