---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 30m
  values:
    broker:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/broker
        tag: v1.12.0@sha256:5d5bbed5d07b27efeff3bdb96f8864e814885fb286238bea7d11985b346e5282
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
    controller:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/controller
        tag: v1.9.1@sha256:e3c0c9864c2f98757caecda6aee5b12a50a468b8c48c1e571104fdc1481b0c32
      excludedNamespaces:
        - kguardian
    database:
      resources:
        limits:
          cpu: 6
    frontend:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/frontend
        tag: v1.11.1@sha256:7fc8ad596421b922b39c8bc25edf8fe9adb638f0ab2fbda7ef5d39280cdfd147
