---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 30m
  values:
    broker:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/broker
        tag: v1.12.4@sha256:83f7556a7571ceb3b31da4be7852b85144859ded37e48c37931f25c31d49b180
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
    controller:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/controller
        tag: v1.9.3@sha256:3ac168f505ce9b8f37a379a9d00dce0ef357eaa29cf108b5925f909448c3de22
      excludedNamespaces:
        - kguardian
    database:
      resources:
        limits:
          cpu: 6
    frontend:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/frontend
        tag: v1.11.4@sha256:4521895ec0ec2b0605012a49c9dd49928f8490e2ddb66b44def57a7806843521
