---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix

resources:
  - continuwuity/ks.yaml
  - heisenbridge/ks.yaml
  - livekit/ks.yaml
  - lk-jwt-service/ks.yaml
  - mautrix-signal/ks.yaml
  - mautrix-whatsapp/ks.yaml
  - namespace.yaml
