---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bluesky-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bluesky-secret
    creationPolicy: Owner
    template:
      data:
        PDS_JWT_SECRET: "{{ .JWT_SECRET }}"
        PDS_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: "{{ .PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX }}"
  dataFrom:
    - extract:
        key: bluesky
