---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: livekit
    creationPolicy: Owner
    template:
      data:
        livekit.yaml: |
          port: 7880
          bind_addresses:
            - ""
          rtc:
            tcp_port: 7881
            port_range_start: 50100
            port_range_end: 50110
            external_ip: 92.222.247.160
            use_external_ip: false
            enable_loopback_candidate: false
            turn_servers:
              - host: turn.erwanleboucher.dev
                port: 3478
                protocol: udp
                secret: "{{ .livekit_turn_secret }}"
              - host: turn.erwanleboucher.dev
                port: 3478
                protocol: tcp
                secret: "{{ .livekit_turn_secret }}"
              - host: turn.erwanleboucher.dev
                port: 5349
                protocol: tls
                secret: "{{ .livekit_turn_secret }}"
          keys:
            {{ .api_key }}: {{ .api_secret }}
  dataFrom:
    - extract:
        key: livekit
    - extract:
        key: continuwuity
