---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: livekit
    creationPolicy: Owner
    template:
      data:
        livekit.yaml: |
          port: 7880
          bind_addresses:
            - ""
          rtc:
            tcp_port: 7881
            port_range_start: 50100
            port_range_end: 50110
            ips:
              includes:
                - 10.42.0.0/16
            stun_servers:
              - turn.erwanleboucher.dev:3478
            turn_servers:
              - host: turn.erwanleboucher.dev
                port: 5349
                protocol: tls
                secret: "{{ .SHARED_SECRET }}"
              - host: turn.erwanleboucher.dev
                port: 3478
                protocol: udp
                secret: "{{ .SHARED_SECRET }}"
            use_external_ip: false
            enable_loopback_candidate: false
          room:
            auto_create: false
          turn:
            enabled: false
          log_level: info
          keys:
            "{{ .api_key }}": "{{ .api_secret }}"
  dataFrom:
    - extract:
        key: livekit
    - extract:
        key: stunner
