---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: towonel-agent
spec:
  interval: 1h
  path: ./kubernetes/apps/network/towonel-agent/app
  postBuild:
    substitute:
      APP: towonel-agent
      APP_NAMESPACE: network
      VPS_IP: 92.222.247.160
      VPS_IP6: 2001:41d0:20a:900::c7e
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
