---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: continuwuity
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: continuwuity
  components:
    - ../../../../components/volsync/cold
  dependsOn:
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: "./kubernetes/apps/matrix/continuwuity/app"
  postBuild:
    substitute:
      VOLSYNC_CRON_LOCAL: "20 23,3,9 * * *"
      APP: continuwuity
      APP_NAMESPACE: matrix
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  timeout: 5m
  wait: false
