# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app continuwuity
spec:
  chartRef:
    kind: OCIRepository
    name: continuwuity
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      continuwuity:
        type: statefulset
        containers:
          app:
            image:
              repository: forgejo.ellis.link/continuwuation/continuwuity
              tag: v26.6.1-maxperf
            env:
              CONDUWUIT_CONFIG: /etc/conduwuit/conduwuit.toml
              TOKIO_WORKER_THREADS: "2"
              TZ: Europe/Paris
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1536Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
          - path: /backups
            subPath: backups
      conduwuit-toml:
        type: secret
        name: continuwuity
        globalMounts:
          - path: /etc/conduwuit/conduwuit.toml
            subPath: conduwuit.toml
            readOnly: true
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - "matrix.erwanleboucher.dev"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
    service:
      app:
        controller: continuwuity
        ports:
          http:
            port: 8080
