# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app continuwuity
spec:
  chartRef:
    kind: OCIRepository
    name: continuwuity
  interval: 1h
  values:
    defaultPodOptions:
      dnsConfig:
        nameservers:
          - "127.0.0.1"
        options:
          - name: ndots
            value: "1"
        searches:
          - cluster.local
      dnsPolicy: None
      nodeSelector:
        kubernetes.io/hostname: paris
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      continuwuity:
        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        initContainers:
          unbound:
            restartPolicy: Always
            image:
              repository: docker.io/madnuttah/unbound
              tag: 1.25.1-3@sha256:1184c6210e56348ffdc446f31eb3108d6d0844ecfd18cf7081ca4ebe87ae8de8
            env:
              DISABLE_SET_PERMS: "true"
              HEALTHCHECK_PORT: "53"
              TZ: Europe/Paris
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec: &probeDnsExec
                    command:
                      - /usr/local/unbound/sbin/healthcheck.sh
                  initialDelaySeconds: 15
                  periodSeconds: 60
                  timeoutSeconds: 30
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  exec: *probeDnsExec
                  initialDelaySeconds: 2
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
        containers:
          app:
            image:
              repository: forgejo.ellis.link/continuwuation/continuwuity
              tag: main-maxperf@sha256:5efeec73426c820e3a6714b0fcfd29295a998b8b1074aa22869979e71682fb36
            env:
              CONDUWUIT_CONFIG: /etc/conduwuit/conduwuit.toml
              TOKIO_WORKER_THREADS: "4"
              TZ: Europe/Paris
            probes:
              liveness:
                enabled: true
                custom: true
                spec: &probeApp
                  tcpSocket:
                    port: 8080
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness:
                enabled: true
                custom: true
                spec: *probeApp
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8080
                  periodSeconds: 5
                  failureThreshold: 120
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                memory: 1536Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          continuwuity:
            app:
              - path: /data
              - path: /backups
                subPath: backups
      conduwuit-toml:
        type: secret
        name: continuwuity
        advancedMounts:
          continuwuity:
            app:
              - path: /etc/conduwuit/conduwuit.toml
                subPath: conduwuit.toml
                readOnly: true
      oidc-secret:
        type: secret
        name: kanidm-continuwuity-oidc
        advancedMounts:
          continuwuity:
            app:
              - path: /etc/continuwuity/oidc_secret
                subPath: client-secret
                readOnly: true
      tmp:
        type: emptyDir
      unbound:
        type: configMap
        name: unbound-configmap
        advancedMounts:
          continuwuity:
            unbound:
              - path: /usr/local/unbound/unbound.conf
                subPath: unbound.conf
      unbound-iana:
        type: emptyDir
        advancedMounts:
          continuwuity:
            unbound:
              - path: /usr/local/unbound/iana.d
    route:
      app:
        hostnames:
          - "matrix.erwanleboucher.dev"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
    service:
      app:
        controller: continuwuity
        ports:
          http:
            port: 8080
