---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: kubectl-mcp
spec:
  image: docker.io/rohitghumare64/kubectl-mcp-server:1.24.0
  transport: streamable-http
  mcpPort: 8080
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  podTemplateSpec:
    spec:
      serviceAccountName: kubectl-mcp
