---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.7.2@sha256:c9c111440f233740a57998177cd7d5c9e8160c99dd0d958bc4ddf56a3de0fc9a
  transport: streamable-http
  proxyPort: 8080
  env:
    - name: SEARXNG_URL
      value: http://searxng.selfhosted.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
