---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.3.4@sha256:21e8f17f02e9c4e1e98f9c5dd6d478066671673316971a6323d0c919693f902c
  transport: streamable-http
  proxyPort: 8080
  env:
    - name: SEARXNG_URL
      value: http://searxng.selfhosted.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
