---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.3.2@sha256:d811b890c5ee6d39ed89bdca72f9af12a994127de2608532e8e5396c6b9632a8
  transport: streamable-http
  proxyPort: 8080
  env:
    - name: SEARXNG_URL
      value: http://searxng.selfhosted.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
