---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - models/qwen3.6/ks.yaml
  - models/gemma/ks.yaml
