---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pangolin-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.0
    digest: sha256:c42e9d81f7c61d879586c13ff4db300f49c047fdb341fb62dca8f1a2328a0c33
  url: oci://ghcr.io/eleboucher/charts/pangolin-operator
